### PR TITLE
Basic Cleanup

### PR DESCRIPTION
**Pull request by jonpage999**
No functional changes, small fixes to JS (move a semi-colon, explicit variable declarations), formatting updates to bring consistent formatting across the file (based on tab size of 2). 

Changes are being submitted to support future JS update pull request show changes clearly.

### CODE REVIEW

**Comment by cmhughes** [comment]
Many thanks, that's really helpful, and I'm really grateful for the improvements. 

If you have a recommended formatting tool, do let me know!

**Comment by jonpage999** [comment]
I'm currently the PHPStorm IDE because I have a license for it, and matched the formatting settings as closely as I could to the project. 

JetBrains do have a WebStorm IDE freely available for non-commercial use that should offer the same features, but I'm sure there must be standalone formatters that would do the job too.

**Comment by cmhughes** [comment]
Great, thanks.

You'll see that for the example files I have a basic formatter at:

https://github.com/cmhughes/a11y-slides-math/blob/8a2a052544162e63026ed2d53074c98f9c11734b/examples/example-creation.py#L105

I might see if I can make that more portable so that the main template file runs through it. 

Contributions/thoughts welcome :)

**Comment by cmhughes** [comment]
If there's a way to do clean up with github actions or pre-commit, so much the better.

**Pull request merged**
